[build]
  base = "react-interactive-comments-section"

[dev]
  functions = "netlify"

[build.environment]
  REACT_APP_API_URL = "netlify"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200