[build]
  base = "react-interactive-comments-section"
functions = "react-interactive-comments-section/interactive-comments-section/netlify/functions"

[dev]
  functions = "react-interactive-comments-section/interactive-comments-section/netlify/functions"

[build.environment]
  REACT_APP_API_URL = "react-interactive-comments-section/interactive-comments-section/netlify/functions"

[functions]
  directory = "react-interactive-comments-section/interactive-comments-section/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200