[build]
  command = "npm run build"
  publish = "react-interactive-comments-section/build"
  functions = "interactive-comments-section/netlify/functions"

[build.environment]
  REACT_APP_API_URL = "/.netlify/functions/api"