[build]
  command = "npm run-script build"
  publish = "react-interactive-comments-section/build"
  functions = "interactive-comments-section/netlify/functions"

[dev]
  functions = "interactive-comments-section/netlify/functions"

[build.environment]
  REACT_APP_API_URL = "/.netlify/functions/api"

[functions]
  directory = "interactive-comments-section/netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200