[build]
  base = "interactive-comments-section"

[dev]
  functions = "interactive-comments-section/netlify/functions"

[build.environment]
  REACT_APP_API_URL = "netlify/functions"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200