[build]
  base = "react-interactive-comments-section"

[dev]
  functions = "functions"

[build.environment]
  REACT_APP_API_URL = "functions"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200