[build]
  base = "react-interactive-comments-section"
functions = "../netlify/functions/api"

[dev]
  functions = "netlify/functions/api"

[build.environment]
  REACT_APP_API_URL = "netlify/functions/api"

[functions]
  directory = "netlify/functions/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200